export const GET_CHARACTER_BY_ID = 'GET_CHARACTER_BY_ID';
export const GET_CHARACTERS_DATA = 'GET_CHARACTERS_DATA';
export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';
export const FILL_CHARACTERS_DATA = 'FILL_CHARACTERS_DATA';
export const CLEAR_CHARACTERS_DATA = 'CLEAR_CHARACTERS_DATA';
