export const GET_LOCATION_BY_ID = 'GET_LOCATION_BY_ID';
export const GET_LOCATIONS_DATA = 'GET_LOCATIONS_DATA';
export const FILL_LOCATIONS_DATA = 'FILL_LOCATIONS_DATA';
export const CLEAR_LOCATIONS_DATA = 'CLEAR_LOCATIONS_DATA';
