export const GET_EPISODE_BY_ID = 'GET_EPISODE_BY_ID';
export const GET_EPISODES_DATA = 'GET_EPISODES_DATA';
export const FILL_EPISODES_DATA = 'FILL_EPISODES_DATA';
export const CLEAR_EPISODES_DATA = 'CLEAR_EPISODES_DATA';
